### ISSUE TITLE
Malformed information to push an image

### ISSUE THREAD

**Issue by isantospardo** [openshift/registry-image-widgets#22]
In okd 3.11 I have noticed that the suggestion to tag and push an image (in builds-> images -> <image>) showed has a duplicated `project name` and `namespace`

(e.g. $ `sudo docker tag myimage openshift-registry<domain>/<myproject>/<myimage>/<myproject>/<myimage>:tag`

I couldn't find in the code anything wrong, happy to push a fix if anyone give me a hand

**Comment by eekbatani** [comment]
I'll try looking into it and let you know if I figure it out.
